services:
  web:
    build: .
    user: "root"
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_HMR_HOST=localhost
      - VITE_HMR_CLIENT_PORT=5173
    volumes:
      - .:/app
    ports:
      - "5173:5173"
      - "24678:24678"
    command: sh -lc "npm run dev -- --host 0.0.0.0"